//
// Created by xgallom on 10/6/19.
//

#ifndef SPRINTER_SPRINTER_CORE_INCLUDE_CORE_DEFINES_H
#define SPRINTER_SPRINTER_CORE_INCLUDE_CORE_DEFINES_H

// Enable logging
#define ENABLE_LOG_RELEASE

#if defined(BUILD_TYPE_RELEASE) && !defined(ENABLE_LOG_RELEASE)
#define DISABLE_LOG
#endif

#endif //SPRINTER_SPRINTER_CORE_INCLUDE_CORE_DEFINES_H
